In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
data = pd.read_csv("/content/drive/MyDrive/Folder lilis, oki jangan sentuh/colab lilis/IMDB Dataset Deep Learning/IMDB Dataset.csv")

In [5]:
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [6]:
data.tail()

                                                  review sentiment
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

In [7]:
data["sentiment"].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [8]:
data.replace({"sentiment": {"positive": 1, "negative": 0}}, inplace=True)

In [9]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [10]:
train_data, test_data = train_test_split(data, test_size = 0.2, random_state=42)

In [11]:
train_data.shape

(40000, 2)

In [12]:
test_data.shape

(10000, 2)

In [13]:
train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)

In [14]:
train_data.shape

(40000, 2)

In [15]:
test_data.shape

(10000, 2)

In [16]:
tokenizer = Tokenizer(num_words = 5000)
tokenizer.fit_on_texts(train_data["review"])

In [17]:
tokenizer = Tokenizer(num_words= 5000)
tokenizer.fit_on_texts(train_data["review"])

In [18]:
X_train = pad_sequences(tokenizer.texts_to_sequences(train_data["review"]), maxlen=200)
X_test = pad_sequences(tokenizer.texts_to_sequences(test_data["review"]), maxlen=200)

In [19]:
X_train

array([[1935,    1, 1200, ...,  205,  351, 3856],
       [   3, 1651,  595, ...,   89,  103,    9],
       [   0,    0,    0, ...,    2,  710,   62],
       ...,
       [   0,    0,    0, ..., 1641,    2,  603],
       [   0,    0,    0, ...,  245,  103,  125],
       [   0,    0,    0, ...,   70,   73, 2062]], dtype=int32)

In [20]:
X_test

array([[   0,    0,    0, ...,  995,  719,  155],
       [  12,  162,   59, ...,  380,    7,    7],
       [   0,    0,    0, ...,   50, 1088,   96],
       ...,
       [   0,    0,    0, ...,  125,  200, 3241],
       [   0,    0,    0, ..., 1066,    1, 2305],
       [   0,    0,    0, ...,    1,  332,   27]], dtype=int32)

In [21]:
Y_train = train_data["sentiment"]
Y_test = test_data["sentiment"]

In [22]:
Y_train

39087    0
30893    0
45278    1
16398    0
13653    0
        ..
11284    1
44732    1
38158    0
860      1
15795    1
Name: sentiment, Length: 40000, dtype: int64

In [23]:
Y_test

33553    1
9427     1
199      0
12447    1
39489    0
        ..
28567    0
25079    1
18707    1
15200    0
5857     1
Name: sentiment, Length: 10000, dtype: int64

MODEL TRAINING

In [24]:
model = Sequential()
model.add(Embedding(input_dim=5000, output_dim=128, input_length=200))
model.add(LSTM(units=128, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(1, activation="sigmoid"))

In [25]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [27]:
model.fit(X_train, Y_train, epochs= 5, batch_size=64, validation_split=0.2)

Epoch 1/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 213s 408ms/step - accuracy: 0.7190 - loss: 0.5456 - val_accuracy: 0.8455 - val_loss: 0.3659
Epoch 2/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 205s 410ms/step - accuracy: 0.8544 - loss: 0.3487 - val_accuracy: 0.8429 - val_loss: 0.3547
Epoch 3/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 206s 411ms/step - accuracy: 0.8810 - loss: 0.2954 - val_accuracy: 0.8514 - val_loss: 0.3373
Epoch 4/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 205s 409ms/step - accuracy: 0.8903 - loss: 0.2693 - val_accuracy: 0.8779 - val_loss: 0.3222
Epoch 5/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 206s 412ms/step - accuracy: 0.9101 - loss: 0.2362 - val_accuracy: 0.8760 - val_loss: 0.3189

In [28]:
loss, accuracy = model.evaluate(X_test, Y_test)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

313/313 ━━━━━━━━━━━━━━━━━━━━ 38s 118ms/step - accuracy: 0.8784 - loss: 0.3054
Test Loss: 0.3029
Test Accuracy: 0.8791

In [29]:
def predictive_system(review):
  sequence= tokenizer.texts_to_sequences([review])
  padded_sequence = pad_sequences(sequence, maxlen=200)
  prediction = model.predict(padded_sequence)
  sentiment = "positive" if prediction > 0.5 else "negative"
  return sentiment

In [30]:
predictive_system("halo")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 436ms/step

'negative'

In [31]:
# 1. Menyimpan dan Mengunduh Tokenizer
import joblib
from google.colab import files

# Menyimpan objek tokenizer ke file .pkl
joblib.dump(tokenizer, "tokenizer.pkl")

# Mengunduh tokenizer ke komputer lokal
files.download("tokenizer.pkl")

# ----------------------------------------------------

# 2. Menyimpan dan Mengunduh Model Keras/TensorFlow
from google.colab import files

# Menyimpan model (asumsi menggunakan Keras/TensorFlow)
model.save("model_pert10.h5")

# Mengunduh model ke komputer lokal
files.download("model_pert10.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.